# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92f3e3cddb28d744bc33caa09281ac99c9785c45587fa40cb7b8487c4389e38995628d5b5936cef47f72bce1f73f155f2b1ccae67ed61dd1fec8a6bc7832df91

test:
  secret_key_base: 87242a7a1dc7496c360f945639af7c55c119260f32ea06e0f8c1049c90f861944c7ffba459eb1023bb4b8ee5ae674892697897f8dae36af45f3edf2e924920ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
